apiVersion: "networking.istio.io/v1alpha3"
kind: "VirtualService"
metadata:
  name: "<clientName-datetime>"
  nameSpace: null
spec:
  hosts:
  - "<hostname>"
  - "newHost.com"
  - "newHost.com"
  - "newHost.com1713766150216"
  - "newHost1713777077184"
  - "newHost1713777286833"
  - "newHost1713777456957"
  - "newHost1713777829345"
  - "newHost1713782925498"
  - "newHost1713789702114"
  - "newHost1713789918623"
  - "newHost1713834088205"
  - "newHost1713834487144"
  gateways:
  - "apiwiz-system/apiwiz-gateway"
  http:
  - route:
    - destination:
      - host: "apibuilder-agent"
        port:
          port: 0
